//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CML.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.CML_Attachments = new HashSet<CML_Attachments>();
            this.Tests = new HashSet<Test>();
            this.CML_Approvals = new HashSet<CML_Approvals>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int RequestID { get; set; }
        public string Name { get; set; }
        public string CMLNumber { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> RequestedBy { get; set; }
        public int BusinessUnitID { get; set; }
        public string ProjectNumber { get; set; }
        public string DeviationNumber { get; set; }
        public string EWRNumber { get; set; }
        public Nullable<bool> DirectorApprovalRequired { get; set; }
        public int StatusID { get; set; }
        public int PriorityID { get; set; }
        public int DispositionID { get; set; }
        public Nullable<System.DateTime> RetentionDate { get; set; }
        public string Phone { get; set; }
        public string TestObjectives { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> DateRequired { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> TestsStarted { get; set; }
        public Nullable<System.DateTime> TestsFinished { get; set; }
        public int RequestTypeID { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<int> TotalSamples { get; set; }
        public string WatchList { get; set; }
        public string ClosureNotes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CML_Attachments> CML_Attachments { get; set; }
        public virtual CML_Disposition CML_Disposition { get; set; }
        public virtual CML_Location CML_Location { get; set; }
        public virtual CML_Priority CML_Priority { get; set; }
        public virtual CML_RequestType CML_RequestType { get; set; }
        public virtual CML_Status CML_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
        public virtual CML_User CML_User { get; set; }
        public virtual CML_BusinessUnit CML_BusinessUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CML_Approvals> CML_Approvals { get; set; }
        public virtual Request Request1 { get; set; }
        public virtual Request Request2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
