//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CML.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.CML_Attachments = new HashSet<CML_Attachments>();
            this.Samples = new HashSet<Sample>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int TestID { get; set; }
        public Nullable<int> CMLRequest { get; set; }
        public Nullable<int> TestDef { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public string Comments { get; set; }
        public Nullable<int> TotalSamples { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> TestStarted { get; set; }
        public Nullable<System.DateTime> TestFinished { get; set; }
        public Nullable<double> SamplePreparations { get; set; }
        public Nullable<double> SampleAnalysis { get; set; }
        public Nullable<double> DataAnalysis { get; set; }
        public Nullable<double> Reports { get; set; }
        public Nullable<double> Cleaning { get; set; }
        public Nullable<double> Total { get; set; }
        public string Name { get; set; }
        public string Abbrev { get; set; }
        public string Determines { get; set; }
        public string SampleType { get; set; }
        public string SampleSize { get; set; }
        public string ClosureNotes { get; set; }
    
        public virtual CML_TestDefinition CML_TestDefinition { get; set; }
        public virtual Request Request { get; set; }
        public virtual CML_User CML_User { get; set; }
        public virtual CML_Status CML_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CML_Attachments> CML_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sample> Samples { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
